GET http://localhost:3000/api/categories
###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Drink"
}
###
PUT http://localhost:3000/api/categories/
Content-Type: application/json

{
    "name": "makanan update"
}
###
DELETE http://localhost:3000/api/categories/65036c3287c2ee3d4539c9c3
###


GET http://localhost:3000/api/tags
###
POST http://localhost:3000/api/tags
Content-Type: application/json

{
    "name": "tag4"
}
###
PUT http://localhost:3000/api/tags/65036e2d64bc0f62915480f5
Content-Type: application/json

{
    "name": "tag 4 update"
}
###
DELETE http://localhost:3000/api/tags/65036e2d64bc0f62915480f5